from .prompts import STORY_PROMPT, SCREENWRITER_PROMPT, CARTOON_IMAGE_PROMPT, ENCYCLO_PROMPT

__all__ = [
    "STORY_PROMPT",
    "SCREENWRITER_PROMPT",
    "CARTOON_IMAGE_PROMPT",
    "ENCYCLO_PROMPT",
]